"""Partition the GDG corpus into N synthetic users — one oplog each.

Used by the per-user density probes. It
produced examples/sw3_*, sw6_*, sw12_*, sw24_* and ph12_*, the fixtures behind
the finding that the detector's floor is OCCURRENCES PER INTENT (~6 for a first
cluster, ~10 for reliable recovery) and not episode density. Those fixtures are
regenerated by this script, so they are not committed.

CLE need. Every fixture so far is ONE user, so nothing in this repository has
ever exercised the shape a population level reads: several independent
topologies that may or may not share intents. This writes that shape.

WHAT THIS IS AND IS NOT — stated here so no result built on it can quietly
overclaim. The users are synthetic slices of a single generator's output, so two
users sharing a planted intent carry text from the SAME generator and are
therefore closer than two real users would be. Anything measured on this corpus
is an upper bound, never an estimate.

Overlap EMERGES from a seeded draw. Assigning one intent per user, or building
the overlap by hand, would plant the answer — the exact shape of the v1 failure,
one level up.

The seven task intents are drawn from; `qa`, `noise` and `abandon` are
background traffic present for everyone, because they are what makes detection
non-trivial (an intent that has no competition is not detected, it is read off).
"""

from __future__ import annotations

import argparse
import collections
import json
import random
import sys
from pathlib import Path

EXAMPLES = Path(__file__).resolve().parent
sys.path.insert(0, str(EXAMPLES.parent))

SOURCE = EXAMPLES / "prompt_history_gdg.jsonl"

#: Intents a user may or may not have. Drawn from; never assigned round-robin.
TASK_INTENTS = (
    "events", "newsletter", "speakers", "sponsors",
    "agenda_meetup", "agenda_workshop", "venue_policy",
)
#: Present for everyone: background traffic, not a signal.
BACKGROUND = ("qa", "noise", "abandon")


def planted_intent(thread_id: str) -> str:
    """The intent a thread was planted under (`events-1-0` -> `events`)."""
    parts = thread_id.split("-")
    return "-".join(parts[:-2]) if len(parts) > 2 else parts[0]


def _threads_by_intent(records: list[dict]) -> dict[str, list[str]]:
    threads: dict[str, list[str]] = collections.defaultdict(list)
    seen: set[str] = set()
    for record in records:
        thread = record["thread_id"]
        if thread in seen:
            continue
        seen.add(thread)
        threads[planted_intent(thread)].append(thread)
    return threads


def partition(records: list[dict], users: int, per_user: tuple[int, int], seed: int):
    """(assignment, matrix) — which intents each user drew, and the records.

    Background threads are split disjointly across users so no two users share a
    literal thread: sharing an INTENT is the signal under test, sharing a thread
    would be a duplicate.
    """
    rng = random.Random(seed)
    threads = _threads_by_intent(records)
    low, high = per_user

    drawn = {
        f"user{i + 1}": sorted(rng.sample(TASK_INTENTS, rng.randint(low, high)))
        for i in range(users)
    }

    # Each intent's threads are dealt round-robin among the users that drew it,
    # so two users sharing an intent get DIFFERENT episodes of it.
    owner: dict[str, str] = {}
    for intent, intent_threads in threads.items():
        holders = (
            [u for u, picked in drawn.items() if intent in picked]
            if intent in TASK_INTENTS
            else list(drawn)  # background: everyone, disjointly
        )
        if not holders:
            continue
        shuffled = list(intent_threads)
        rng.shuffle(shuffled)
        for index, thread in enumerate(shuffled):
            owner[thread] = holders[index % len(holders)]

    by_user: dict[str, list[dict]] = collections.defaultdict(list)
    for record in records:
        holder = owner.get(record["thread_id"])
        if holder is not None:
            by_user[holder].append(record)
    return drawn, by_user


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--users", type=int, default=3)
    parser.add_argument("--min-intents", type=int, default=3)
    parser.add_argument("--max-intents", type=int, default=5)
    parser.add_argument("--seed", type=int, default=1789)
    parser.add_argument(
        "--disjoint", action="store_true",
        help="NEGATIVE CONTROL: give every user intents no other user has. Any "
             "level-2 grouping on this corpus is reading its own construction.",
    )
    parser.add_argument("--prefix", default="prompt_history_")
    args = parser.parse_args()

    records = [json.loads(line) for line in SOURCE.read_text().splitlines()]

    if args.disjoint:
        # Deal the seven task intents so that no two users share any.
        rng = random.Random(args.seed)
        pool = list(TASK_INTENTS)
        rng.shuffle(pool)
        drawn = {
            f"user{i + 1}": sorted(pool[i::args.users]) for i in range(args.users)
        }
        threads = _threads_by_intent(records)
        owner = {}
        for intent, intent_threads in threads.items():
            holders = [u for u, picked in drawn.items() if intent in picked] or list(drawn)
            for index, thread in enumerate(intent_threads):
                owner[thread] = holders[index % len(holders)]
        by_user = collections.defaultdict(list)
        for record in records:
            by_user[owner[record["thread_id"]]].append(record)
    else:
        drawn, by_user = partition(
            records, args.users, (args.min_intents, args.max_intents), args.seed
        )

    manifest = {"seed": args.seed, "disjoint": args.disjoint, "users": {}}
    for user in sorted(drawn):
        rows = by_user.get(user, [])
        path = EXAMPLES / f"{args.prefix}{user}.jsonl"
        path.write_text("\n".join(json.dumps(r) for r in rows) + "\n")
        present = sorted({planted_intent(r["thread_id"]) for r in rows})
        manifest["users"][user] = {
            "drawn": drawn[user],
            "present": present,
            "messages": len(rows),
            "threads": len({r["thread_id"] for r in rows}),
            "history": path.name,
        }

    # The user x intent matrix. Without it no result on this corpus is
    # interpretable — how many users hold each intent IS the ground truth a
    # level-2 grouping would have to recover.
    shared = collections.Counter()
    for user in manifest["users"].values():
        for intent in user["present"]:
            shared[intent] += 1
    manifest["users_per_intent"] = dict(sorted(shared.items(), key=lambda kv: -kv[1]))

    out = EXAMPLES / f"{args.prefix}manifest.json"
    out.write_text(json.dumps(manifest, indent=1))

    print(f"{'user':8} {'msgs':>5} {'thr':>4}  intents")
    for user, info in manifest["users"].items():
        print(f"{user:8} {info['messages']:>5} {info['threads']:>4}  "
              f"{', '.join(info['present'])}")
    print("\nusers per intent (emergent, not constructed):")
    for intent, count in manifest["users_per_intent"].items():
        print(f"  {intent:18} {count}")
    print(f"\nwrote {len(manifest['users'])} histories + {out.name}")


if __name__ == "__main__":
    main()
