"""Raise sites the mutation sweep found unguarded, each pinned by what it refuses.

SCOPE: bucket 1 (embedder-agnostic). Every assertion is about WHICH input is
refused and HOW: an exit code, an exception type, a message. No vector space is
under test; where a command builds the stub embedder, it fails before embedding.

One test per SITE, not per exception class (cle-core-contracts, item 9). The CLI
tests assert the exception TYPE as well as the exit code, and that is the point
of them: remove a refusal and the command usually crashes a few lines further
down, also with exit code 1. A test that checked only the code would stay green
over a guard that no longer exists.
"""

from pathlib import Path

import pytest
import yaml
from typer.testing import CliRunner

from cle.cli.main import app
from cle.detect.embedders import UnknownCalibrationError, embedding_config_for, open_embedder
from cle.lifecycle.topology import render_diff
from cle.store.backends import InMemoryStore

ROOT = Path(__file__).resolve().parent.parent.parent
HISTORY = ROOT / "examples" / "prompt_history_adversarial.jsonl"


@pytest.fixture
def runner() -> CliRunner:
    return CliRunner()


@pytest.fixture
def spec(tmp_path) -> Path:
    """A spec written here, not read from `examples/`.

    The agent YAMLs there are gitignored and regenerated by `make_fixture.py`,
    so a clean clone has none. Every test using this one is refused before its
    centroid is compared to anything: a unit vector in the stub's 64 dimensions
    is enough, and nothing is embedded.
    """
    path = tmp_path / "status_report_agent.yaml"
    path.write_text(yaml.safe_dump({
        "name": "status_report",
        "detected_from": {"authored": "human"},
        "components": ["#blocks/recap_format", "#blocks/team_context"],
        "trigger": {"centroid": [1.0] + [0.0] * 63, "embedder_id": "stub:hashed64"},
    }, sort_keys=False))
    return path


def _said(result) -> str:
    text = result.output or ""
    try:
        text += result.stderr or ""
    except ValueError:  # a click that does not capture stderr separately
        pass
    return text


def _refused(result, code: int, message: str) -> None:
    """The command stopped ON PURPOSE, with this code, saying this."""
    assert result.exit_code == code, _said(result)
    assert isinstance(result.exception, SystemExit), (
        f"expected a deliberate exit, got {type(result.exception).__name__}: the "
        "refusal is gone and the command crashed further down instead"
    )
    assert message in _said(result), _said(result)


# --- global options: cle/cli/main.py, the app callback ----------------------

def test_an_unknown_store_backend_is_a_usage_error(runner, tmp_path, monkeypatch) -> None:
    monkeypatch.delenv("CLE_STORE", raising=False)
    result = runner.invoke(app, ["--store", "bogus", "ps", "--state-dir", str(tmp_path)])
    _refused(result, 2, "--store must be one of")


def test_an_unknown_embedder_kind_is_a_usage_error(runner, tmp_path, monkeypatch) -> None:
    """Without the refusal, `ps` would run and exit 0 under a space nobody named."""
    monkeypatch.delenv("CLE_EMBEDDER", raising=False)
    result = runner.invoke(app, ["--embedder", "bogus", "ps", "--state-dir", str(tmp_path)])
    _refused(result, 2, "--embedder must be one of")


# --- cle build ---------------------------------------------------------------

def test_a_malformed_replay_window_is_a_usage_error(runner, tmp_path, spec) -> None:
    result = runner.invoke(app, [
        "build", str(spec), "--history", str(HISTORY), "--replay-window", "10x",
        "--model-id", "stub-model-1", "--state-dir", str(tmp_path),
    ])
    _refused(result, 2, "window must look like 30d or 48h")


def test_an_empty_history_is_refused_before_anything_is_written(runner, tmp_path, spec) -> None:
    empty = tmp_path / "empty.jsonl"
    empty.write_text("")
    state = tmp_path / "state"
    result = runner.invoke(app, [
        "build", str(spec), "--history", str(empty), "--model-id", "stub-model-1",
        "--state-dir", str(state),
    ])
    _refused(result, 1, "history is empty")
    assert not state.exists(), "the refusal must come before the state dir is touched"


def test_a_build_that_cannot_resolve_its_components_exits_cleanly(runner, tmp_path, spec) -> None:
    """Resolution fails (no component seeded), and the CLI says so and stops.

    Without the exit, control falls through to the report, which reads an
    `image` that was never assigned.
    """
    no_components = tmp_path / "components"
    no_components.mkdir()
    result = runner.invoke(app, [
        "build", str(spec), "--history", str(HISTORY), "--replay-window", "40d",
        "--components", str(no_components), "--model-id", "stub-model-1",
        "--state-dir", str(tmp_path / "state"),
    ])
    _refused(result, 1, "build failed")


def test_a_refused_build_leaves_the_store_as_it_found_it(runner, tmp_path, spec) -> None:
    """Invariant 3 on the CLI path: the seeds are writes too.

    One of the spec's two components is on disk, so seeding HAS something to
    write before resolution fails on the other. Seeding straight into the store
    left that block and its ref behind in a state dir the build was refused on.
    """
    components = tmp_path / "components"
    components.mkdir()
    (components / "recap_format.yaml").write_text(
        (ROOT / "examples" / "components" / "recap_format.yaml").read_text())
    state = tmp_path / "state"
    result = runner.invoke(app, [
        "build", str(spec), "--history", str(HISTORY), "--replay-window", "40d",
        "--components", str(components), "--model-id", "stub-model-1",
        "--state-dir", str(state),
    ])
    _refused(result, 1, "build failed")
    from cle.store.backends import open_store

    assert open_store(state).list_refs("") == []
    assert not [p for p in (state / "store").rglob("*") if p.is_file()]


# --- cle decline ---------------------------------------------------------------

def test_decline_refuses_a_reason_that_is_not_a_decline_reason(runner, tmp_path) -> None:
    """`cost_regression` is in the vocabulary, but it names a descent, not a refusal."""
    state = tmp_path / "state"
    result = runner.invoke(app, ["decline", "ghost", "--reason", "cost_regression",
                                 "--state-dir", str(state)])
    _refused(result, 2, "decline --reason must be one of")
    assert not state.exists(), "refused before the state dir is opened"


# --- commands addressing an agent the topology does not hold ----------------

def test_run_refuses_an_agent_the_topology_does_not_hold(runner, tmp_path) -> None:
    result = runner.invoke(app, ["run", "ghost", "--workspace", "w", "--state-dir", str(tmp_path)])
    _refused(result, 1, "unknown agent 'ghost'")


def test_tag_refuses_an_agent_the_topology_does_not_hold(runner, tmp_path) -> None:
    result = runner.invoke(app, ["tag", "ghost", "trial", "--state-dir", str(tmp_path)])
    _refused(result, 1, "unknown agent 'ghost'")


def test_decline_refuses_an_agent_the_topology_does_not_hold(runner, tmp_path) -> None:
    result = runner.invoke(app, ["decline", "ghost", "--state-dir", str(tmp_path)])
    _refused(result, 1, "unknown agent 'ghost'")


# --- the embedding substrate --------------------------------------------------

def test_the_live_embedder_refuses_to_start_without_a_credential(monkeypatch) -> None:
    """Reached through `open_embedder`, never by importing the live class.

    No network: the constructor refuses before any client exists. Removing the
    refusal hands `None` to the SDK, which fails with an error that names neither
    of the two ways to fix it.
    """
    for name in ("CLE_VERTEX_PROJECT", "GEMINI_API_KEY", "GOOGLE_API_KEY"):
        monkeypatch.delenv(name, raising=False)
    with pytest.raises(RuntimeError, match="needs CLE_VERTEX_PROJECT"):
        open_embedder("real")


def test_a_topology_cannot_be_keyed_by_an_embedder_that_names_no_space() -> None:
    """The message is what bites: without this site, the next check still
    raises the same class, saying there is no calibration for `None`."""
    with pytest.raises(UnknownCalibrationError, match="exposes no embedder_id"):
        embedding_config_for(object())


# --- the topology history ----------------------------------------------------

def test_diff_names_the_version_it_cannot_find() -> None:
    """A bare dict lookup would raise KeyError too, carrying only the ref."""
    with pytest.raises(KeyError, match="unknown topology version topology/v1"):
        render_diff(InMemoryStore(), "topology/v1", "topology/v2")
